version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: manif-postgres
    env_file:
      - .env  # Load env file data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:  
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Data persist karega
    networks:
      - manif-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U manif_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service 1: User Service
  user-service:
    build: ./user_service
    container_name: user_service
    env_file:
      - .env
    ports:
      - "${USER_SERVICE_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - DEBUG_MODE=${DEBUG_MODE}
    depends_on:
      postgres-db:
        condition: service_healthy  # Database ready hone ka wait karega
    restart: always
    networks:
      - manif-network

  # Service 2: Greeting Service
  greeting-service:
    build: ./greeting_service
    container_name: greeting_service
    ports:
      - "${GREETING_SERVICE_PORT}:8000"
    env_file:
      - .env
    restart: always
    networks:
      - manif-network


volumes:
  postgres-data:  # Named volume (data persist karega even after container restart)

  
# Network definition (Dono services ek dusre se baat kar sakti hain)
networks:
  manif-network:
    driver: bridge