apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:  # stringData use karein, K8s automatically base64 encode kar dega
  POSTGRES_USER: "manif_user"
  POSTGRES_PASSWORD: "12345678"
  POSTGRES_DB: "manif_db"